//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBoardDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComment()
        {
            this.tblComment1 = new HashSet<tblComment>();
        }
    
        public int CommentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> MainComment { get; set; }
        public string CommentContent { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComment> tblComment1 { get; set; }
        public virtual tblComment tblComment2 { get; set; }
        public virtual tblPost tblPost { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
