//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBoardDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTranslation
    {
        public string Language { get; set; }
        public string FormName { get; set; }
        public string ControlName { get; set; }
        public string Description { get; set; }
    }
}
