//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBoardDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTranslation
    {
        public int TranslationID { get; set; }
        public string TranslationKey { get; set; }
        public int LanguageID { get; set; }
        public string Translation { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual tblLanguage tblLanguage { get; set; }
    }
}
